Vagrant.configure("2") do |c|
  c.berkshelf.enabled = false if Vagrant.has_plugin?("vagrant-berkshelf")
  c.vm.box = "/Users/jvarghese/tdd/centos65.box"
  c.vm.hostname = "default-centos65"
  c.vm.network(:forwarded_port, {:guest=>80, :host=>8880})
  c.vm.network(:forwarded_port, {:guest=>81, :host=>8881})
  c.vm.synced_folder ".", "/vagrant", disabled: true
  c.vm.provider :virtualbox do |p|
  end
end
